# @package _global_

optim:
  warmup_steps: 2500
  batch_size: 64
  total_steps: 16384
  grad_acc: 8

model:
  name: 'google/t5-v1_1-small'
  compile: true # Pytorch 2.0

checkpoint:
  every_steps: 2000